feat: update document on how to use private component repository
kubebb/website pull request #58
Opened 2023-08-31 08:46 UTC by zqq454224016

Fix:
feat #22

2023-09-01 02:15 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +2. 部署一个仓库
fix the markdownlint warnings

2023-09-01 02:15 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +## 部署私有组件仓库
this is for `体验私有组件仓库`

2023-09-05 05:38 UTC, bjwswang requested changes
any progress?

2023-09-06 05:57 UTC, zqq454224016 commented on docs/quick-start/core_quickstart.md
> +2. 部署一个仓库
Is there any problem here?

2023-09-06 06:11 UTC, bjwswang reviewed
how to verify whether chartmuseum is running well

2023-09-11 03:17 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +```
需要告诉开发者怎么来验证chartmuseum是否部署成功

2023-09-11 03:19 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +2. 部署一个仓库
这里应该叫 "添加仓库"

2023-09-11 03:19 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +1. 在官方仓库中部署chartmuseum
部署一个私有仓库

2023-09-11 03:19 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +创建仓库
“使用一下命令”

2023-09-11 03:19 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +apiVersion: core.kubebb.k8s.com.cn/v1alpha1
这段yaml可以删除掉

2023-09-11 03:20 UTC, bjwswang commented on docs/quick-start/core_quickstart.md
> +kubectl apply -f repository_chartmuseum.yaml
可以用链接

2023-09-11 03:20 UTC, bjwswang requested changes
需要更改，使用起来步清晰

2023-09-12 06:16 UTC, closed without merging

2023-09-12 06:36 UTC, zqq454224016 commented on docs/quick-start/core_quickstart.md
> +kubectl apply -f repository_chartmuseum.yaml
components 里面的example是添加basic auth