feat: add frontend-low-code docs
kubebb/website pull request #79
Opened 2023-10-16 03:05 UTC by Jandiasnow

ref: https://github.com/kubebb/website/issues/38

2023-10-17 01:52 UTC, bjwswang requested changes
@Jandiasnow Please fix the comments post by markdownlint bot

2023-10-17 01:52 UTC, bjwswang commented on docs/lowcode-development/development/frontend-low-code.md
> +
@Jandiasnow twoo much blanks lines here.

2023-10-17 01:52 UTC, bjwswang commented on docs/lowcode-development/development/frontend-low-code.md
> +首先我们需要在云梯工作台【应用管理】-【新增应用】下创建一个应用，如果您已有可用的应用则可以跳过本步，如下图所示，我们创建一个名为 `Hello World` 的空白应用：
add a blank line here .

2023-10-17 02:55 UTC, Carrotzpc commented on docs/lowcode-development/development/frontend-low-code.md
> +接下来我们需要创建一个页面来实现 `Hello World` 的功能，如下所示，当前我们还没有页面模板（已有的页面），可以不选择：
与图中命名最好一致 `HelloWorld`，图中的命名多了一个 `w`。。。

2023-10-17 08:32 UTC, Carrotzpc commented
@bjwswang 看下，应该没问题了

2023-10-17 14:03 UTC, bjwswang approved these changes

2023-10-18 02:40 UTC, bjwswang commented on docs/lowcode-development/development/frontend-low-code.md
> +    ![添加页面数据](images/page_add_api.png)
@Jandiasnow

2023-10-18 02:41 UTC, bjwswang commented on docs/lowcode-development/development/frontend-low-code.md
> +接下来我们需要创建一个页面来实现 `Hello World` 的功能，如下所示，当前我们还没有页面模板（已有的页面），可以不选择：
@Jandiasnow

2023-10-18 03:42 UTC, merged