update develop-hello-world
kubebb/website pull request #81
Opened 2023-10-17 05:52 UTC by littsummer

Write the component release process
![image](https://github.com/kubebb/website/assets/41468710/239ba856-8aba-455f-8318-c149ea62041a)

2023-10-17 06:42 UTC, Carrotzpc commented on docs/lowcode-development/development/develop-hello-world.md
> +云梯低码平台发布一个应用的完整流程：新增应用 -> 创建分支 -> 新增页面 -> 设计页面 -> git 提交 -> 发布应用。 发布之前先设计一个应用，请参见[前端层基于低码 Kit 的开发](./fronend-low-code.md)。 发布管理包括两部分，应用发布和组件仓库管理。
之前文件命名拼写错误，跳转的时候可以改成 `./frontend-low-code.md`

2023-10-17 06:42 UTC, Carrotzpc commented on docs/lowcode-development/development/develop-hello-world.md
> +- 应用的维护者、拥有者才有发布应用的权限。
建议增加一个说明，提醒用户发布前应先在 Git 面板中提交修改，发布的应用中不会包含未提交的修改。

2023-10-18 02:42 UTC, bjwswang requested changes
@littsummer  本地能跑起来么? 可以的话，加个截图吧

2023-10-18 05:28 UTC, littsummer commented
> @littsummer 本地能跑起来么? 可以的话，加个截图吧

![image](https://github.com/kubebb/website/assets/41468710/31be0e11-ce99-403c-af53-6ecb4d2581d8)

2023-10-18 05:34 UTC, merged