@feature: remove config.dev, use env DEPLOY_PLATFORM
kubebb/website pull request #84
Opened 2023-10-27 09:17 UTC by Vsion

2023-10-27 09:23 UTC, bjwswang approved these changes

2023-10-27 09:23 UTC, bjwswang commented
@Vsion test failed

2023-10-27 09:26 UTC, Vsion commented
![image](https://github.com/kubebb/website/assets/11804448/76e6834e-9f08-4be3-8b0b-77646dfa5fe1)
新增依赖导致的 ?

2023-10-27 09:26 UTC, Vsion commented
![image](https://github.com/kubebb/website/assets/11804448/721717a3-d17a-49a3-a6fe-755605339ad2)

2023-10-31 01:45 UTC, bjwswang commented
@Vsion 
![image](https://github.com/kubebb/website/assets/30621793/b979aba7-fe19-4020-9429-5598afc3ffab)
看起来是引用了内部tenxcloud的库，这个地方删掉是不是就行了？

2023-10-31 01:45 UTC, bjwswang requested changes
修复下问题

2023-11-06 09:14 UTC, closed without merging